### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by frozenbanana** [CptMaistro/case-7-react#1]
Godkänd: Nej
Åtgärd: Det ska vara möjligt för en användare att boka en föreställning. Det minsta möjliga hade varit en knapp för varje föreställning "Book Show". `onClick` så ska användaren bli notifierad att användaren har blivit bokad. Utöver det är du godkänd så lägg till en sista push och få det fixat! 💪 
---

## Komponentsuppdelning
Du har fått in en komponent `Nav` som du använder dig men samtidigt ser jag också MovieList som du inte använder och istället så har du kopierat hela innehållet och lagt det i `Movie.js`.
Resten av filerna i `Components` är inte komponenter utan hela sidor. Jag rekommenderar att du lägger dem i ny mapp `Pages`.

## Git-commits
Jag ser enligt dina commits så har du börjat arbeta på Caset den 19de september. Det går mig att undra vad du har gjort innan dess. Idén med att vi vill att ni committar ert arbete det är vi kan se att ni är delaktiga i kursen under hela case-perioden.

Utöver det så kan jag tydligt se vad du har arbetat på under varje kommit. Det är bra!

## Allmän kodstil
Du har precis som många andra skrivit hämtat cinema-data flera gånger. Det är onödigt och kostar användaren extra mycket data(=pengar). Min starka rekommendation är att du lägger fetch-koden i `App.js` och skickar med `cinemaData` som prop till dina sidor.

**Comment by CptMaistro** [comment]
lämnade två meddelanden på teams om detta. så säger till om det här utifall du missar det på teams.

**Comment by frozenbanana** [comment]
Du är godkänd! Bra jobbat.
